// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RXAI.Context;

#nullable disable

namespace RXAI.Migrations
{
    [DbContext(typeof(RXAIContext))]
    [Migration("20250227203212_UpdatePrescriptions")]
    partial class UpdatePrescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RXAI.Entities.ActiveIngredient", b =>
                {
                    b.Property<string>("DrugBankID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ICDCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("StrengthUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DrugBankID");

                    b.HasIndex("ICDCode");

                    b.ToTable("ActiveIngredients");
                });

            modelBuilder.Entity("RXAI.Entities.Disease", b =>
                {
                    b.Property<string>("ICDCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ICDCode");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("RXAI.Entities.Patient", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("PhoneNumber");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("RXAI.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<DateTime?>("DispenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PrescriptionDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("RXAI.Entities.PrescriptionTrade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AtcCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DispenseTradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DispensedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AtcCode");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PrescriptionTrade");
                });

            modelBuilder.Entity("RXAI.Entities.TradeName", b =>
                {
                    b.Property<string>("AtcCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DrugBankID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Indication")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ManufactureCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PharmaceuticalForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QuantityStock")
                        .HasColumnType("int");

                    b.Property<string>("SideEffect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AtcCode");

                    b.HasIndex("DrugBankID");

                    b.ToTable("TradeNames");
                });

            modelBuilder.Entity("RXAI.Entities.ActiveIngredient", b =>
                {
                    b.HasOne("RXAI.Entities.Disease", "Disease")
                        .WithMany("ActiveIngredients")
                        .HasForeignKey("ICDCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("RXAI.Entities.Prescription", b =>
                {
                    b.HasOne("RXAI.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PhoneNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("RXAI.Entities.PrescriptionTrade", b =>
                {
                    b.HasOne("RXAI.Entities.TradeName", "Trade")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("AtcCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RXAI.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionTrades")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("RXAI.Entities.TradeName", b =>
                {
                    b.HasOne("RXAI.Entities.ActiveIngredient", "ActiveIngredient")
                        .WithMany("Trades")
                        .HasForeignKey("DrugBankID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveIngredient");
                });

            modelBuilder.Entity("RXAI.Entities.ActiveIngredient", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("RXAI.Entities.Disease", b =>
                {
                    b.Navigation("ActiveIngredients");
                });

            modelBuilder.Entity("RXAI.Entities.Patient", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("RXAI.Entities.Prescription", b =>
                {
                    b.Navigation("PrescriptionTrades");
                });

            modelBuilder.Entity("RXAI.Entities.TradeName", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
